apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ws-middle-cache
  labels:
    app: ws-middle-cache
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ws-middle-cache
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: ws-middle-cache
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: ws-middle-cache
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}