apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ws-middle-cache
  labels:
    app: ws-middle-cache
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: ws-middle-cache
    release: {{ .Release.Name }}